//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchEngine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordId { get; set; }
        public string RecordQuery { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual Credential Credential { get; set; }
    }
}
